name: algerian_billing_app
description: A Flutter billing application tailored for Algerian stores.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # Database
  sqflite: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.0

  # PDF & Printing
  pdf: ^3.10.0
  printing: ^5.11.0

  # Thermal Printer
  print_bluetooth_thermal: ^1.1.2

  # Localization
  intl: ^0.20.3

  # Navigation
  go_router: ^14.0.0

  # Scanner
  mobile_scanner: ^5.1.0
  vibration: ^3.1.8

  # File sharing & picking
  share_plus: ^10.0.0
  file_picker: ^8.0.0

  # UI
  google_fonts: ^6.1.0
  uuid: ^4.2.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
